# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('lang', models.CharField(max_length=30)),
                ('font_fam', models.CharField(max_length=30)),
                ('font_size', models.IntegerField()),
            ],
        ),
    ]
