# Generated by Django 2.0.6 on 2018-06-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('title_page', models.BooleanField(default=False)),
                ('lang', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('German', 'German'), ('French', 'French'), ('Italian', 'Italian'), ('Dutch', 'Dutch'), ('Polish', 'Polish')], default=True, max_length=30)),
                ('font_fam', models.CharField(choices=[('/Library/Fonts/Times New Roman.ttf', 'Times New Roman'), ('/Library/Fonts/Arial.ttf', 'Arial'), ('/Library/Fonts/Helvetica.dfont', 'Helvetica')], max_length=50)),
                ('font_size', models.CharField(choices=[('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=2)),
                ('nouns', models.BooleanField(default=False)),
                ('verbs', models.BooleanField(default=False)),
                ('adjs', models.BooleanField(default=False)),
                ('other', models.BooleanField(default=False)),
                ('fast_translate', models.BooleanField(default=False)),
                ('sub_all', models.BooleanField(default=False)),
                ('page_nums', models.BooleanField(default=False)),
            ],
            options={
                'db_tablespace': 'tables',
            },
        ),
    ]
