# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationmodel',
            name='adjs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='fast_translate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='nouns',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='other_pos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='page_nums',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='phrase',
            field=models.TextField(default='Enter text here'),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='sub_all',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translationmodel',
            name='verbs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='font_fam',
            field=models.CharField(choices=[(b'Times New Roman', b'/Library/Fonts/Times New Roman.ttf'), (b'Arial', b'/Library/Fonts/Arial.ttf'), (b'Helvetica', b'/Library/Fonts/Helvetica.dfont')], default=b'/Library/Fonts/Arial.ttf', max_length=30),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='font_size',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29)], default=12),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='lang',
            field=models.CharField(choices=[(b'English', b'English'), (b'Spanish', b'Spanish'), (b'German', b'German'), (b'French', b'French'), (b'Italian', b'Italian'), (b'Dutch', b'Dutch'), (b'Polish', b'Polish')], default='English', max_length=30),
        ),
        migrations.AlterField(
            model_name='translationmodel',
            name='title',
            field=models.CharField(default='translation', max_length=50),
        ),
    ]
