# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss_webapp', '0003_auto_20170902_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationmodel',
            name='font_size',
            field=models.IntegerField(choices=[(10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30)], default=12),
        ),
    ]
