# coding: utf-8
"""
PLAYGROUND:

    Used for playing around with whatever I want.  (Not for GitHub.)
"""
#from speecharts import *
from language_learner.language_learner import LanguageLearner
import main.bliss_web.bliss_app.bliss_webapp.blisscribe_py.excerpts as excerpts


#eng_txts = excerpts.english_texts
#fra_txts = excerpts.french_texts
#shakespeare = excerpts.shakespearean_texts

lil_prince = excerpts.little_prince
petit_prince = excerpts.petit_prince

ll = LanguageLearner()
#print ll.crossmatch([lil_prince, petit_prince], ["English", "French"])
#print ll.text_synonyms(petit_prince, language="French")
#ll.learn_sentences(lil_prince)
print ll.find_ngrams("\n\n".join([excerpts.alice_in_wonderland, lil_prince]))
#print ll.find_ngrams("\n".join([lil_prince, excerpts.alice_in_wonderland]))
#print ll.classify_text(lil_prince, language="English") #ll.text_synonyms(lil_prince, language="English")

# goal: split words into a distinct, minimum # of categories
# e.g. determiners, pronouns, verbs, nouns, adjectives/adverbs

cluster = {u'all': [u'there', u'an', u'what', u'no'],
           u'just': [u'really'],
           u'go': [u'get', u'see', u'do'],
           u'yes': [],
           u'had': [u'was', u'have'],
           u'to': [u'in', u'of'],
           u'going': [],
           u'has': [u'didn'],
           u'then': [u'when', u'well'],
           u'them': [u'him'],
           u'good': [u'one', u'an', u'well'],
           u'get': [u'see', u'be', u'go', u'have'],
           u'know': [u'want'],
           u'they': [u'she', u'he'],
           u'not': [u'be', u'have'],
           u'now': [u'when'],
           u'him': [u'them'],
           u'like': [],
           u'did': [],
           u'didn': [u'don', u'has', u'or', u'really', u'be'],
           u'she': [u'they', u'he'],
           u'where': [u'how'],
           u'right': [],
           u'some': [u'an', u'no'],
           u'back': [],
           u'see': [u'get', u'be', u'go', u'do', u'have'],
           u'are': [u'have', u'were'],
           u'our': [],
           u'really': [u'just', u'didn'],
           u'what': [u'here', u'all', u'when'],
           u'for': [u'in', u'as'],
           u'got': [u'let'],
           u'be': [u'not', u'didn', u'get', u'see', u'have'],
           u'we': [u'there'],
           u'here': [u'what'],
           u'let': [u'look', u'got'],
           u'come': [u'look'],
           u'by': [],
           u'on': [u'in', u'at'],
           u'about': [],
           u'her': [],
           u'oh': [],
           u'of': [u'to'],
           u'could': [u'can'],
           u'or': [u'didn'],
           u'one': [u'good', u'time', u'an', u'this'],
           u'your': [u'my', u'an'],
           u'from': [],
           u'would': [],
           u'there': [u'we', u'all'],
           u'been': [u'an'],
           u'was': [u'is', u'had'],
           u'tell': [],
           u'that': [],
           u'but': [],
           u'with': [],
           u'he': [u'they', u'she'],
           u'me': [],
           u'look': [u'come', u'let'],
           u'this': [u'one', u'an', u'his'],
           u'up': [u'out'],
           u'us': [],
           u'will': [],
           u'can': [u'could'],
           u'were': [u'are'],
           u'my': [u'your', u'an', u'his'],
           u'say': [],
           u'and': [],
           u'have': [u'had', u'not', u'get', u'see', u'be', u'are'],
           u'do': [u'see', u'go'],
           u'is': [u'was'],
           u'it': [u'you'],
           u'an': [u'good', u'my', u'one', u'your', u'all', u'some', u'been', u'this', u'no'],
           u'as': [u'for', u'so'],
           u'his': [u'my', u'this'],
           u'at': [u'on'],
           u'want': [u'don', u'know'],
           u'in': [u'for', u'on', u'to'],
           u'if': [u'when'],
           u'no': [u'an', u'all', u'some'],
           u'when': [u'then', u'if', u'now', u'what'],
           u'how': [u'where'],
           u'take': [],
           u'you': [u'it'],
           u'out': [u'up'],
           u'who': [],
           u'why': [],
           u'man': [],
           u'a': [u'the'],
           u'don': [u'want', u'didn'],
           u'well': [u'then', u'good'],
           u'think': [],
           u'so': [u'as'],
           u'time': [u'one'],
           u'the': [u'a']}

clusters_shakespeare = {u'all': [u'then'],
           u'go': [u'come'],
           u'yes': [u'follow'],
           u'had': [u'were'],
                        u'to': [u'not'],
           u'going': [u'descend'],
           u'has': [u'sings'],
           u'do': [u'know'],
                        u'them': [u'him'],
           u'his': [u'my'],
           u'get': [u'bid'],
           u'know': [u'say'],
           u'they': [u'we'],
                        u'not': [u'me'],
           u'now': [u'why'],
           u'him': [u'me'],
           u'like': [u'if'],
           u'did': [u'do'],
                        u'she': [u'why'],
           u'where': [u'why'],
           u'right': [u'answer'],
           u'some': [u'much'],
                        u'back': [u'perform'],
           u'see': [u'tell'],
           u'are': [u'do'],
           u'our': [u'my'],
                        u'out': [u'about'],
           u'what': [u'how'],
           u'for': [u'but'],
                        u'got': [u'celebrated', u'rob', u'sadly'],
           u'be': [u'not'],
           u'we': [u'they'],
                        u'here': [u'tell'],
           u'let': [u'see'],
           u'come': [u'do'],
           u'by': [u'at'],
                        u'on': [u'for'],
           u'about': [u'set'],
           u'her': [u'them'],
           u'oh': [u'come'],
                        u'of': [u'in'],
           u'could': [u'must'],
           u'or': [u'if'],
           u'one': [u'men'],
                        u'your': [u'my'],
           u'from': [u'tell'],
           u'would': [u'must'],
           u'there': [u'now'],
                        u'hey': [u'non'],
           u'been': [u'laid'],
           u'was': [u'now'],
           u'tell': [u'call'],
                        u'that': [u'it'],
           u'but': [u'for'],
           u'with': [u'in'],
           u'he': [u'it'],
                        u'me': [u'him'],
           u'look': [u'gall'],
           u'this': [u'that'],
           u'say': [u'know'],
                        u'will': [u'may'],
           u'can': [u'should'],
           u'were': [u'had'],
           u'my': [u'the'],
                        u'and': [u'that'],
           u'then': [u'come'],
           u'is': [u'for'],
           u'it': [u'that'],
                        u'an': [u'mine'],
           u'as': [u'for'],
           u'good': [u'well'],
           u'at': [u'by'],
                        u'want': [u'crowd'],
           u'in': [u'for'],
           u'if': [u'when'],
           u'no': [u'do'],
                        u'when': [u'if'],
           u'how': [u'why'],
           u'take': [u'hold'],
           u'you': [u'i'],
                        u'who': [u'why'],
           u'why': [u'where'],
           u'man': [u'men'],
           u'a': [u'my'],
                        u'don': [u'seen'],
           u'i': [u'you'],
           u'well': [u'now'],
           u'think': [u'marshall', u'repeat'],
                        u'so': [u'you'],
           u'time': [u'death'],
           u'the': [u'my']}

clusters_french = {u'peux': [u'veux'],
           u'peut': [u'pourrait'],
           u'comme': [u'mais'],
           u'veux': [u'peux'],
                   u'le': [u'un'],
           u'mais': [u'et'],
           u'la': [u'une'],
           u'tu': [u'je'],
           u'te': [u're'],
                   u'non': [u'moi'],
           u'de': [u'et'],
           u'moi': [u'toi'],
           u'sont': [u'fait'],
           u'mon': [u'ce'],
                   u'du': [u'de'],
           u'voir': [u'trouver'],
           u'faire': [u'voir'],
                   u'o\xf9': [u'impitoyable', u'activit\xe9'],
           u'dit': [u'mais'],
           u'fait': [u'dire'],
                   u'oui': [u'non'],
           u'en': [u'elle'],
           u'\xe7a': [u'toi'],
           u'et': [u'il'],
                   u'jamais': [u'rien'],
           u'es': [u'veux'],
           u'ici': [u'voir'],
           u'est': [u'avait'],
                   u'l\xe0': [u'ici'],
           u'bien': [u'pas'],
           u'sais': [u'crois'],
           u'sur': [u'dans'],
                   u'lui': [u're'],
           u'avoir': [u'prendre'],
           u'chose': [u'fois'],
           u'les': [u'des'],
                   u'que': [u'si'],
           u'dire': [u'voir'],
           u'qui': [u'elle'],
           u'je': [u'tu'],
                   u'm\xeame': [u'roi'],
           u'\xe0': [u'sur'],
           u'\xeatre': [u'conna\xeetre'],
                   u'juste': [u'seul'],
           u'oh': [u'maintenant'],
           u'cette': [u'ma'],
           u'tous': [u'ceux'],
                   u'plus': [u're'],
           u'ils': [u'elles'],
           u'bon': [u'serpent'],
           u'vraiment': [u'alors'],
                   u'ou': [u're'],
           u'comment': [u'pourquoi'],
           u'\xe9tait': [u'fut'],
           u'votre': [u'morale'],
                   u'ce': [u'du'],
           u'son': [u'l'],
           u'vais': [u'peux'],
           u'ont': [u'as'],
           u'suis': [u'trouve'],
                   u'avec': [u'sur'],
           u'avez': [u'aviez'],
           u'toi': [u'moi'],
           u'ton': [u'temps'],
                   u'\xe9t\xe9': [u'd\xe9sob\xe9ir'],
           u'vous': [u're'],
           u'on': [u'elle'],
           u'tr\xe8s': [u'bien'],
                   u'me': [u'te'],
           u'ma': [u'cette'],
           u'des': [u'les'],
           u'dans': [u'sur'],
           u'pour': [u'que'],
                   u'merci': [u'seulement'],
           u'un': [u'le'],
           u'pourquoi': [u'quoi'],
           u'va': [u'pouvait'],
                   u'ai': [u'avais'],
           u'aussi': [u're'],
           u'as': [u'avais'],
           u'au': [u'le'],
           u'il': [u'elle'],
                   u'par': [u'sur'],
           u'pas': [u'bien'],
           u'quand': [u'car'],
           u'alors': [u'moi'],
                   u'ne': [u'je'],
           u'deux': [u'trois'],
           u'tout': [u'e'],
           u'quoi': [u'nouveau'],
                   u'une': [u'la'],
           u'rien': [u'moi'],
           u'elle': [u'il'],
           u'maintenant': [u'arrive'],
                   u'a': [u'e'],
           u'si': [u'que'],
           u'y': [u'm'],
           u'nous': [u'moi'],
           u'sa': [u'ma'],
           u'se': [u'ne']}

clusters_polish = {u'gdy': [u'teraz'],
           u'dobrze': [u'm\xf3wi\u0142em'],
           u'ale': [u'a'],
                   u'wszystko': [u'w\u0142a\u015bciwie'],
           u'go': [u'nawet'],
           u'prosz\u0119': [u'wcale'],
                   u'ci\u0119': [u'nawet'],
           u'sobie': [u'ci'],
           u'musz\u0119': [u'mog\u0119'],
           u'ty': [u'ja'],
                   u'tu': [u'ty'],
           u'przepraszam': [u'ciekawe'],
           u'to': [u'jest'],
           u'jak': [u'co'],
           u'do': [u'z'],
                   u'b\u0119dzie': [u'gra'],
           u'domu': [u'przysi\u0119g\u0142ych'],
           u'ju\u017c': [u'jednak'],
                   u'nawet': [u'wolno'],
           u'naprawd\u0119': [u'niczego'],
           u'chc\u0119': [u'przychod\u017a', u'dbam'],
                   u'ten': [u'd\xf3\u0142'],
           u'teraz': [u'nigdy'],
           u'ze': [u'w\u0142a\u015bciwie'],
                   u'za': [u'w\u0142a\u015bciwie'],
           u'pani': [u'przecie\u017c'],
           u's\u0105': [u'by\u0142o'],
                   u'dla': [u'od'],
           u'ich': [u'czas'],
           u'mo\u017cesz': [u'chcia\u0142'],
           u'kiedy': [u'ja'],
                   u'mo\u017ce': [u'musi'],
           u'bardzo': [u'tak'],
           u'm\xf3j': [u'uszy'],
           u'nic': [u'jeste\u015b'],
                   u'gdzie': [u'je\u017celi'],
           u'si\u0119': [u'to'],
           u'bo': [u'ja'],
           u'tego': [u'tym'],
                   u'wi\u0119c': [u'ale'],
           u'jestem': [u'jeste\u015b'],
           u'mnie': [u'ale'],
           u'by': [u'zaczyna'],
                   u'on': [u'czego'],
           u'od': [u'dla'],
           u'o': [u'do'],
           u'w': [u'na'],
           u'ci': [u'ty'],
                   u'co': [u'czy'],
           u'ona': [u'przecie\u017c'],
           u'\u017ceby': [u'trzeba'],
           u'\u017ce': [u'ale'],
                   u'by\u0142': [u'by\u0142o'],
           u'mamy': [u'grasz'],
           u'wiem': [u'wiedzia\u0142a'],
                   u'przez': [u'jeszcze'],
           u'ja': [u'ty'],
           u'zrobi\u0107': [u'wreszcie'],
                   u'dlaczego': [u'przecie\u017c'],
           u'jej': [u'nigdy'],
           u'je\u015bli': [u'je\u017celi'],
                   u'po': [u'o'],
           u'jego': [u'jej'],
           u'nigdy': [u'nikt'],
           u'by\u0107': [u'im'],
                   u'ma': [u'nigdy'],
           u'dzi\u0119kuj\u0119': [u'jem'],
           u'mi': [u'sobie'],
           u'mu': [u'wam'],
                   u'kto': [u'c\xf3\u017c'],
           u'by\u0142o': [u'by\u0142'],
           u'z': [u'do'],
                   u'chyba': [u'przedtem'],
           u'czy': [u'ale'],
           u'tutaj': [u'w\u0142a\u015bciwie'],
                   u'te\u017c': [u'ciesz\u0119'],
           u'jest': [u'ma'],
           u'tam': [u'naprawd\u0119'],
                   u'tak': [u'to'],
           u'no': [u'chcia\u0142abym'],
           u'na': [u'w'],
           u'nas': [u'was'],
                   u'j\u0105': [u'by\u0142o'],
           u'pan': [u'w\u0142a\u015bciwie'],
           u'mog\u0119': [u'mo\u017cna'],
                   u'tym': [u'nim'],
           u'chcesz': [u'my\u015blisz'],
           u'ciebie': [u'wody'],
                   u'co\u015b': [u'zrobi\u0107'],
           u'tylko': [u'ju\u017c'],
           u'nie': [u'\u017ce'],
           u'mam': [u'ma'],
                   u'a': [u'ale'],
           u'jeste\u015b': [u'pami\u0119tam'],
           u'i': [u'ale'],
           u'wiesz': [u'jem'],
                   u'masz': [u'naprawi\u0142em', u'macie', u'potrafi', u'pr\xf3buj'],
           u'jeszcze': [u'tutaj']}

clusters2_polish = {u'gdy': [u'wszystko'],
           u'dobrze': [u'wiesz'],
           u'ale': [u'a'],
           u'wszystko': [u'wiem'],
                    u'go': [u'mnie'],
           u'prosz\u0119': [u'mog\u0105'],
           u'ci\u0119': [u'powiem'],
           u'sobie': [u'nawet'],
                    u'musz\u0119': [u'mog\u0119'],
           u'ty': [u'on'],
           u'tu': [u'ty'],
           u'przepraszam': [u'kolana'],
                    u'to': [u'co'],
           u'jak': [u'to'],
           u'do': [u'o'],
           u'b\u0119dzie': [u'gra'],
                    u'domu': [u'koz\u0142a'],
           u'ju\u017c': [u'nawet'],
           u'nawet': [u'tylko'],
                    u'naprawd\u0119': [u'przecie\u017c'],
           u'chc\u0119': [u'przychod\u017a', u'dbam', u'pomog\u0142o'],
                    u'ten': [u'ona'],
           u'teraz': [u'wiem'],
           u'ze': [u'za'],
           u'za': [u'o'],
           u'pani': [u'wiem'],
                    u's\u0105': [u'byli'],
           u'dla': [u'od'],
           u'ich': [u'was'],
           u'mo\u017cesz': [u'powinno'],
                    u'kiedy': [u'wszystko'],
           u'mo\u017ce': [u'musi'],
           u'bardzo': [u'tak'],
           u'm\xf3j': [u'jeden'],
                    u'nic': [u'ty'],
           u'gdzie': [u'kim'],
           u'si\u0119': [u'to'],
           u'bo': [u'kto'],
           u'tego': [u'mnie'],
                    u'wi\u0119c': [u'jednak'],
           u'jestem': [u'ty'],
           u'mnie': [u'ty'],
           u'by': [u'ty'],
           u'on': [u'ty'],
                    u'dobra': [u'winie'],
           u'od': [u'jeszcze'],
           u'o': [u'po'],
           u'w': [u'na'],
           u'ci': [u'mi'],
                    u'co': [u'to'],
           u'ona': [u'chce'],
                    u'\u017ceby': [u'przynie\u015b', u'zgodzili', u'k\u0142\xf3c\u0105', u'przygotuj',
                                   u'wypadkiem', u'czyni\u0105', u'uratowa\u0142', u'cukrem'],
                    u'\u017ce': [u'czy'],
           u'by\u0142': [u'nawet'],
           u'mamy': [u'niczego'],
           u'wiem': [u'teraz'],
                    u'przez': [u'jeszcze'],
           u'ja': [u'ty'],
                    u'zrobi\u0107': [u'zostan\u0119', u'liczba', u'spodoba\u0142o', u'porabiasz', u'sprzedajesz',
                                     u'zale\u017cy', u'stolik', u'umie\u015bci\u0107', u'przyja\u017anie'],
                    u'dlaczego': [u'wiesz'],
           u'jej': [u'mnie'],
           u'je\u015bli': [u'je\u017celi'],
           u'po': [u'o'],
                    u'jego': [u'jej'],
           u'nigdy': [u'niczego'],
           u'by\u0107': [u'ono'],
           u'ma': [u'tu'],
                    u'dzi\u0119kuj\u0119': [u'jem'],
           u'mi': [u'ci'],
           u'mu': [u'wam'],
           u'kto': [u'bo'],
                    u'by\u0142o': [u'ty'],
           u'z': [u'w'],
           u'chyba': [u'przecie\u017c'],
           u'czy': [u'ty'],
                    u'tutaj': [u'dziewczyna'],
           u'te\u017c': [u'wybra\u0142em', u'ciesz\u0119'],
                    u'jest': [u'to'],
           u'tam': [u'nic'],
           u'tak': [u'co'],
           u'no': [u'wiesz'],
                    u'na': [u'w'],
           u'nas': [u'was'],
           u'j\u0105': [u'by\u0107'],
           u'pan': [u'pani'],
                    u'mog\u0119': [u'musz\u0119'],
           u'tym': [u'nim'],
           u'chcesz': [u'chce'],
                    u'ciebie': [u'wiesz'],
           u'co\u015b': [u'zrobi\u0107'],
           u'tylko': [u'nawet'],
                    u'nie': [u'to'],
           u'mam': [u'masz'],
           u'a': [u'to'],
           u'jeste\u015b': [u'znalaz\u0142'],
                    u'i': [u'to'],
           u'wiesz': [u'wiem'],
           u'masz': [u'mam'],
           u'jeszcze': [u'nic']}

clusters3_polish = {u'gdy': [u'czy'],
           u'dobrze': [u'wiem'],
           u'ale': [u'a'],
           u'wszystko': [u'wiem'],
                    u'go': [u'mnie'],
           u'prosz\u0119': [u'mog\u0105'],
           u'ci\u0119': [u'powiem'],
                    u'sobie': [u'tylko'],
           u'musz\u0119': [u'mog\u0119'],
           u'ty': [u'wiem'],
                    u'tu': [u'ma'],
           u'przepraszam': [u'gdybym'],
           u'to': [u'jak'],
                    u'jak': [u'to'],
           u'do': [u'w'],
           u'b\u0119dzie': [u'idzie'],
                    u'domu': [u'okna'],
           u'ju\u017c': [u'jednak'],
           u'nawet': [u'bo'],
                    u'naprawd\u0119': [u'przecie\u017c'],
                    u'chc\u0119': [u'przychod\u017a', u'dbam', u'pomog\u0142o'],
                    u'ten': [u'ona'],
           u'teraz': [u'tam'],
           u'ze': [u'za'],
           u'za': [u'o'],
                    u'pani': [u'wiem'],
           u's\u0105': [u'mieli'],
           u'dla': [u'u'],
           u'ich': [u'mnie'],
                    u'mo\u017cesz': [u'powinno'],
           u'kiedy': [u'wszystko'],
           u'mo\u017ce': [u'mog\u0119'],
                    u'bardzo': [u'tak'],
           u'm\xf3j': [u'zadanie'],
           u'nic': [u'nikt'],
                    u'gdzie': [u'kim'],
           u'si\u0119': [u'to'],
           u'bo': [u'ja'],
           u'tego': [u'cie'],
                    u'wi\u0119c': [u'jednak'],
           u'jestem': [u'wiem'],
           u'mnie': [u'ja'],
                    u'by': [u'ty'],
           u'on': [u'ona'],
           u'dobra': [u'role'],
           u'od': [u'po'],
                    u'o': [u'po'],
           u'w': [u'na'],
           u'ci': [u'mi'],
           u'co': [u'to'],
           u'ona': [u'ta'],
                    u'\u017ceby': [u'przynie\u015b', u'zgodzili', u'k\u0142\xf3c\u0105',
                                   u'przygotuj', u'czyni\u0105', u'wojskowy'],
                    u'\u017ce': [u'czy'],
           u'by\u0142': [u'ten'],
           u'mamy': [u'niczego'],
                    u'wiem': [u'wiedzia\u0142'],
           u'przez': [u'za'],
           u'ja': [u'ty'],
                    u'zrobi\u0107': [u'zostan\u0119', u'liczba', u'porabiasz', u'zale\u017cy', u'sprzedajesz',
                                     u'stolik', u'umie\u015bci\u0107', u'przyja\u017anie'],
                    u'dlaczego': [u'wiem'],
           u'jej': [u'jego'],
           u'je\u015bli': [u'przecie\u017c'],
                    u'po': [u'o'],
           u'jego': [u'jej'],
           u'nigdy': [u'nikt'],
           u'by\u0107': [u'obecnie'],
                    u'ma': [u'mam'],
           u'dzi\u0119kuj\u0119': [u'jem'],
           u'mi': [u'ci'],
           u'mu': [u'jej'],
                    u'kto': [u'dlaczego'],
           u'by\u0142o': [u'ma'],
           u'z': [u'w'],
           u'chyba': [u'nikt'],
                    u'czy': [u'co'],
           u'tutaj': [u'tobie'],
           u'te\u017c': [u'oddzia\u0142u'],
                    u'jest': [u'to'],
           u'tam': [u'wiem'],
           u'tak': [u'to'],
           u'no': [u'teraz'],
                    u'na': [u'w'],
           u'nas': [u'was'],
           u'j\u0105': [u's\u0142owo'],
                    u'pan': [u'nikt'],
           u'mog\u0119': [u'musz\u0119'],
           u'tym': [u'nim'],
                    u'chcesz': [u'ona'],
           u'ciebie': [u'niej'],
           u'co\u015b': [u'zapomnia\u0142a'],
                    u'tylko': [u'jeszcze'],
           u'nie': [u'to'],
           u'mam': [u'masz'],
           u'a': [u'to'],
                    u'jeste\u015b': [u'ukrywam', u'pami\u0119tam'],
           u'i': [u'w'],
                    u'wiesz': [u'wiedzia\u0142'],
           u'masz': [u'wiem'],
           u'jeszcze': [u'nic']}

